apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-kubernetes-discoveryserver-deployment
spec:
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-discoveryserver
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver
    spec:
      serviceAccount: spring-cloud-kubernetes-discoveryserver
      containers:
        - name: spring-cloud-kubernetes-discoveryserver
          image: springcloud/spring-cloud-kubernetes-discoveryserver:3.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8761
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8761
              path: /actuator/health/liveness
          ports:
            - containerPort: 8761