apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: spring-cloud-kubernetes-discoveryserver
  name: spring-cloud-kubernetes-discoveryserver:view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: spring-cloud-kubernetes-discoveryserver